server:
  port: 8081

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql:///mybatis?&serverTimezone=Asia/Shanghai
  application:
    name: service-provider #将来会作为微服务的名称
mybatis:
  type-aliases-package: com.demo.cloud.serviceprovider.entity
eureka:
  instance:
    lease-renewal-interval-in-seconds: 5  #服务续约  心跳机制的时间间隔
    lease-expiration-duration-in-seconds: 15 #失效过期时间
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    register-with-eureka: true  #服务提供方启动时,会检测该参数是否为true,如果是就注册给eureka
