server:
  port: 8082

spring:
  application:
    name: service-consumer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 5 #拉取服务列表的间隔时间
    fetch-registry: true

#feign默认不会使用hystrix,需要手动开启
feign:
  hystrix:
    enabled: true  #开启Feign的熔断功能
